### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by zhaoyihang873** [scy-phy/ICS-Evasion-Attacks#1]
I just came into contact with anomaly detection. We have an idea to use your attack model and our detection model together to perfect our two models at the same time. The question is, how do you use your model to generate attack data?

**Comment by axoaxel** [comment]
Thanks for your interest. We just updated the Readme, and are in the process of publishing the related paper. An earlier version of the work is available at https://arxiv.org/abs/1907.07487.  Please have a look at the Readme and let us know if you have specific questions.
