### ISSUE TITLE
Dataset question

### ISSUE THREAD

**Issue by moon-aver** [scy-phy/ICS-Evasion-Attacks#3]
Hello

Constrained Concealment Attacks against Reconstruction-based Anomaly Detectors in Industrial Control Systems
I have a question regarding the dataset while I am trying to conduct research by checking the paper and GitHub data.

An error occurred while running GitHub's Blackbox model. After checking, it seems to be a problem caused by the dataset, so we are in the process of resolving the error.

The WADI dataset was requested and downloaded, but
According to the github description, it says to divide the dataset like the BATAL dataset, so I am curious about what criteria should be used to divide it.
I tried to analyze the BATAL dataset classification criteria, but it was difficult to clearly understand the criteria, so I wrote an email.

Also, in the case of the WADI dataset, there are two files, 'WADI_14days_new' and 'WADI_attackdataLABLE', and I am wondering if both can be used.

I would really appreciate it if you could reply after confirmation.

Have a nice day :)

**Comment by axoaxel** [comment]
Hi, thanks for your interest in our work.

As the WADI folder reports, you have to add the ground truth to the WADI_attackdata.csv, based on the timestamps that you should have received with the data. Then you have to extract the attack data and create multiple .csv files, each containing exclusively the anomaly data (the criteria to split them is based on the ground truth i.e., extract the anomalous data). This operation will result in obtaining multiple splits of the dataset, attack_1.csv, attacks_2.csv, etc.

Yes, you will have to use both the .csv you have received. As one is used for training and the other for testing.

Hope this answer clarifies your doubts. Feel free to reach out in case you have more questions.

**Comment by moon-aver** [comment]
For BATADAL dataset
There are 14 divided test_datasets.
Can I create the same 14 files for the WADI dataset?

You also said that you will use both CSV files, one for education and one for testing. Please share how you created the dataset.
In the case of BATADAL, it appears that about 250 pieces of data are contained in each test file.
Is it possible to create 14 csv files by arranging the data contained in WADI's 2 csv files to contain 250 random rows each?

I did not understand the following explanation.
'You need to add ground truth to WADI_attackdata.csv based on the timestamps the WADI folder should receive with the data when reporting. Then we need to extract the attack data and generate several .csv files, each containing only the anomalous data (the splitting criteria is based on the ground truth, i.e. the anomalous data extraction).

**Comment by axoaxel** [comment]
Please read paragraph 5 of the paper., especially 5.1 and 5.2. Where the explanation of the dataset is provided.

In the case of Wadi, there are 15 attacks and not 14 as in Batadal. So you will have to extract 15 attacks. The anomalous is contained in the dataset already, so there is no extraction of random rows involved. To extract the rows that are produced during an attack, you need to rely on the ground truth which you should have received together with the requested data.
